### ISSUE TITLE
Mockup layout

### ISSUE THREAD

**Issue by cbrody** [IIED-org/REDAA#116]

**Comment by ncktrnr** [comment]
See mockups 
[2024-08-27-REDAA-resources-mockups.pdf](https://iied.sharepoint.com/:b:/s/REDAA_iied/EezC_kaMCRhNnaZe8H2C1QsBCvQhg6GYobs8pyg9JFAcwA?e=vlTY2r)

The resource content type is split into 3 main kinds: publication (e.g. PDF), video or other multimedia, and HTML page (e.g. impact story)
 
The main resource page is split into a grid of 2 columns as this will probably fit the content best.
 
The cards for individual resources are included. 

Extra field needed on resources type:

- supporting text
- H2 (optional)
- cover image (rename existing image field)
- main image 

Field group module would be useful for organising admin fields

- [ ] Discussion needed on how to add and format related content on resources

**Comment by cbrody** [comment]
Circulated for comment: https://xd.adobe.com/view/2e580a6c-d4af-4362-83be-6947a410c854-7b0b/
