### ISSUE TITLE
Migrate REDAA site

### ISSUE THREAD

**Issue by cbrody** [IIED-org/REDAA#126]
www.redaa.org
https://prod.redaa.org

- [x] Test prod site
- [x] Feature freeze
- [x] Migrate code & config
- [x] Content freeze - readonlymode?
- [x] Migrate db & files
- [x] Test
- [x] Update DNS etc.
- [x] Test

Launch target: 20241016T11:00

**Comment by stephen-cox** [comment]
@cbrody The REDAA site is now setup on the new server here: https://prod.redaa.org/

Please give it a test and let me know if you find any issues.
